/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPasajero;
import Modelo.Pasajero;
import java.awt.Graphics;
import java.awt.Image;
import java.net.MalformedURLException;
import java.net.URL;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.lang.*;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Javier
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    DefaultTableModel table;
    Vector datosPrincipales = new Vector();

    FondoPanel fondo = new FondoPanel();
    FondoPanel2 fondo2 = new FondoPanel2();
    private ImageIcon imagen;
    private Icon icono;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {

        this.setContentPane(fondo);
        setLocation(300,100);
        setResizable(false);
        initComponents();
        datosPrincipales.addElement("Nombres");
        datosPrincipales.addElement("Apellidos");
        datosPrincipales.addElement("Cedula");
        datosPrincipales.addElement("Origen");
        datosPrincipales.addElement("Destino");
        datosPrincipales.addElement("Fecha");
        datosPrincipales.addElement("Asiento");
        datosPrincipales.addElement("Telefono");
        datosPrincipales.addElement("Clase");
        table = new DefaultTableModel(datosPrincipales, 0);
 
        this.setImagen(jLAeropuerto,"src/Imagenes/los-santos.png");
        this.setImagenes(bntRegistrar,"src/Imagenes/registrar.png");
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        jLNombre = new javax.swing.JLabel();
        jTCiudadDestino = new javax.swing.JTextField();
        jLApellidos = new javax.swing.JLabel();
        jTfApellidos = new javax.swing.JTextField();
        jPanel2 = new FondoPanel2();
        jLabel5 = new javax.swing.JLabel();
        jLAeropuerto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bntRegistrar = new javax.swing.JButton();
        jLRegCompra = new javax.swing.JLabel();
        jLNroAsiento = new javax.swing.JLabel();
        jTfNroAsiento = new javax.swing.JTextField();
        jLClase = new javax.swing.JLabel();
        jcBClase = new javax.swing.JComboBox<>();
        jLCiudadOrigen = new javax.swing.JLabel();
        jTfNombre1 = new javax.swing.JTextField();
        jLCiudadDestino = new javax.swing.JLabel();
        jTCiudadOrigen1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTfCedulaPasaporte = new javax.swing.JTextField();
        jLFecha = new javax.swing.JLabel();
        jDFechaVuelo = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jTfTelefono = new javax.swing.JTextField();
        bntMostrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLNombre.setText("Nombres: ");
        jPanel1.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, 20));
        jPanel1.add(jTCiudadDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 170, 30));

        jLApellidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLApellidos.setText("Apellidos:");
        jPanel1.add(jLApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        jPanel1.add(jTfApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 200, 30));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setText("AEROPUERTO INTERNACIONAL \"LOS SANTOS\"");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));
        jPanel2.add(jLAeropuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 150, 130));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("AEROPUERTO INTERNACIONAL \"LOS SANTOS\"");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("BIENVENIDOS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 190, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 720, 130));

        bntRegistrar.setToolTipText("");
        bntRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(bntRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 60, 60));

        jLRegCompra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLRegCompra.setText("Registrar Vuelo ");
        jPanel1.add(jLRegCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jLNroAsiento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLNroAsiento.setText("Nro Asiento");
        jPanel1.add(jLNroAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        jPanel1.add(jTfNroAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 70, 30));

        jLClase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLClase.setText("Clase: ");
        jPanel1.add(jLClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));

        jcBClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primera Clase", "Bussines", "Turista" }));
        jcBClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBClaseActionPerformed(evt);
            }
        });
        jPanel1.add(jcBClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        jLCiudadOrigen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLCiudadOrigen.setText("Ciudad Origen:");
        jPanel1.add(jLCiudadOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));
        jPanel1.add(jTfNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 200, 30));

        jLCiudadDestino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLCiudadDestino.setText("Destino:");
        jPanel1.add(jLCiudadDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));
        jPanel1.add(jTCiudadOrigen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 170, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cédula/Pasaporte: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));
        jPanel1.add(jTfCedulaPasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 150, 30));

        jLFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLFecha.setText("Fecha de Vuelo:");
        jPanel1.add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));
        jPanel1.add(jDFechaVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Telefono:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));
        jPanel1.add(jTfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 150, 30));

        bntMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(bntMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 60, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Mostrar Vuelos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcBClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcBClaseActionPerformed

    private void bntRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegistrarActionPerformed
         // TODO add your handling code here:
        
        
        ArrayList<Pasajero> listap = new ArrayList<>();
        Controlador.ControladorPasajero ctrlPasajero = new ControladorPasajero();
        Pasajero mod = new Pasajero();
        int ced = Integer.parseInt(jTfCedulaPasaporte.getText());
        mod.setNombres(jTfNombre1.getText());
        mod.setApellidos(jTfApellidos.getText());        
        mod.setNroAsiento(Integer.parseInt(jTfNroAsiento.getText()));
        mod.setCiudadDestino(jTCiudadDestino.getText());
        mod.setCiudadOrigen(jTCiudadOrigen1.getText());
        mod.setClase(jcBClase.getSelectedItem().toString());
        mod.setCedula(ced);
        mod.setFechaVuelo(jDFechaVuelo.getDate());
        mod.setTelefono(Integer.parseInt(jTfTelefono.getText()));
        listap.add(mod);
        if(ctrlPasajero.GuardarDatos(mod)) {
            JOptionPane.showMessageDialog(null, "Registro Completado!");
        } else {
            JOptionPane.showMessageDialog(null, "Error al guardar");
        }
        jTfNombre1.setText("");
        jTfApellidos.setText("");
        jTfNroAsiento.setText("");
        jTCiudadDestino.setText("");
        jTCiudadOrigen1.setText("");
        jTfTelefono.setText("");
        jTfCedulaPasaporte.setText("");
        
    }//GEN-LAST:event_bntRegistrarActionPerformed

    private void bntMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMostrarActionPerformed
        // TODO add your handling code here:
        ListaDeInformacion listaDeInformacion = new ListaDeInformacion();
        listaDeInformacion.setVisible(true);
        
    }//GEN-LAST:event_bntMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    private void setImagen(JLabel lbl, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(),
                        lbl.getHeight(),
                        Image.SCALE_DEFAULT
                )
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }
            private void setImagenes(JButton jB, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        jB.getWidth(),
                        jB.getHeight(),
                        Image.SCALE_DEFAULT
                )
        );
        jB.setIcon(this.icono);
        this.repaint();
        
        }
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntMostrar;
    private javax.swing.JButton bntRegistrar;
    private com.toedter.calendar.JDateChooser jDFechaVuelo;
    private javax.swing.JLabel jLAeropuerto;
    private javax.swing.JLabel jLApellidos;
    private javax.swing.JLabel jLCiudadDestino;
    private javax.swing.JLabel jLCiudadOrigen;
    private javax.swing.JLabel jLClase;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNroAsiento;
    private javax.swing.JLabel jLRegCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTCiudadDestino;
    private javax.swing.JTextField jTCiudadOrigen1;
    private javax.swing.JTextField jTfApellidos;
    private javax.swing.JTextField jTfCedulaPasaporte;
    private javax.swing.JTextField jTfNombre1;
    private javax.swing.JTextField jTfNroAsiento;
    private javax.swing.JTextField jTfTelefono;
    private javax.swing.JComboBox<String> jcBClase;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo2.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);
            super.paint(g);
        }
    }
class FondoPanel2 extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);
            super.paint(g);
        }
    }
}
